### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by doki-nordic** [doki-nordic/my-dockers#1]
* [ ] Handle exceptions in command executable creation function
* [ ] Nice message for user if there are no user editable `bin` directories
* [ ] Delete executables from `bin` directory if they are removed from configuration (`data` directory should contain list of currently active commands)
* [ ] Detect if shared directories was changed and suggest deleting the container.
